//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("inventorySKU.App_GlobalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string AdminGroup_Auth {
            get {
                return ResourceManager.GetString("AdminGroup_Auth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string AdminGroup_CreateAt {
            get {
                return ResourceManager.GetString("AdminGroup_CreateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string AdminGroup_CreateBy {
            get {
                return ResourceManager.GetString("AdminGroup_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string AdminGroup_ID {
            get {
                return ResourceManager.GetString("AdminGroup_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string AdminGroup_IsEnable {
            get {
                return ResourceManager.GetString("AdminGroup_IsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string AdminGroup_Name {
            get {
                return ResourceManager.GetString("AdminGroup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string AdminGroup_UpdateAt {
            get {
                return ResourceManager.GetString("AdminGroup_UpdateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string AdminGroup_UpdateBy {
            get {
                return ResourceManager.GetString("AdminGroup_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string AdminUser_Account {
            get {
                return ResourceManager.GetString("AdminUser_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string AdminUser_AllowWarehouse {
            get {
                return ResourceManager.GetString("AdminUser_AllowWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string AdminUser_ApiPassword {
            get {
                return ResourceManager.GetString("AdminUser_ApiPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string AdminUser_ApiUserName {
            get {
                return ResourceManager.GetString("AdminUser_ApiUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string AdminUser_Auth {
            get {
                return ResourceManager.GetString("AdminUser_Auth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string AdminUser_CreateAt {
            get {
                return ResourceManager.GetString("AdminUser_CreateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string AdminUser_CreateBy {
            get {
                return ResourceManager.GetString("AdminUser_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string AdminUser_Group {
            get {
                return ResourceManager.GetString("AdminUser_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string AdminUser_ID {
            get {
                return ResourceManager.GetString("AdminUser_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string AdminUser_IsEnable {
            get {
                return ResourceManager.GetString("AdminUser_IsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string AdminUser_Name {
            get {
                return ResourceManager.GetString("AdminUser_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string AdminUser_Password {
            get {
                return ResourceManager.GetString("AdminUser_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string AdminUser_TimeZone {
            get {
                return ResourceManager.GetString("AdminUser_TimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string AdminUser_UpdateAt {
            get {
                return ResourceManager.GetString("AdminUser_UpdateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string AdminUser_UpdateBy {
            get {
                return ResourceManager.GetString("AdminUser_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string AttributeErr {
            get {
                return ResourceManager.GetString("AttributeErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Brand_CreateAt {
            get {
                return ResourceManager.GetString("Brand_CreateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Brand_CreateBy {
            get {
                return ResourceManager.GetString("Brand_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Brand_ID {
            get {
                return ResourceManager.GetString("Brand_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Brand_IsEnable {
            get {
                return ResourceManager.GetString("Brand_IsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Brand_IsExport {
            get {
                return ResourceManager.GetString("Brand_IsExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Brand_Name {
            get {
                return ResourceManager.GetString("Brand_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Brand_NetoID {
            get {
                return ResourceManager.GetString("Brand_NetoID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Brand_UpdateAt {
            get {
                return ResourceManager.GetString("Brand_UpdateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Brand_UpdateBy {
            get {
                return ResourceManager.GetString("Brand_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Company_AmazonAccountID {
            get {
                return ResourceManager.GetString("Company_AmazonAccountID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Company_CreateAt {
            get {
                return ResourceManager.GetString("Company_CreateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Company_CreateBy {
            get {
                return ResourceManager.GetString("Company_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Company_eBayAccountID {
            get {
                return ResourceManager.GetString("Company_eBayAccountID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Company_ID {
            get {
                return ResourceManager.GetString("Company_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Company_IsEnable {
            get {
                return ResourceManager.GetString("Company_IsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Company_Name {
            get {
                return ResourceManager.GetString("Company_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Company_ParentID {
            get {
                return ResourceManager.GetString("Company_ParentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Company_RelateID {
            get {
                return ResourceManager.GetString("Company_RelateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Company_ShandowSuffix {
            get {
                return ResourceManager.GetString("Company_ShandowSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Company_UpdateAt {
            get {
                return ResourceManager.GetString("Company_UpdateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Company_UpdateBy {
            get {
                return ResourceManager.GetString("Company_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Condition_Amazon {
            get {
                return ResourceManager.GetString("Condition_Amazon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Condition_Buy_com {
            get {
                return ResourceManager.GetString("Condition_Buy_com", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Condition_CreateAt {
            get {
                return ResourceManager.GetString("Condition_CreateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Condition_CreateBy {
            get {
                return ResourceManager.GetString("Condition_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Condition_eBay {
            get {
                return ResourceManager.GetString("Condition_eBay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Condition_ID {
            get {
                return ResourceManager.GetString("Condition_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Condition_IsEnable {
            get {
                return ResourceManager.GetString("Condition_IsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Condition_Name {
            get {
                return ResourceManager.GetString("Condition_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Condition_NewEgg_com {
            get {
                return ResourceManager.GetString("Condition_NewEgg_com", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Condition_Sears {
            get {
                return ResourceManager.GetString("Condition_Sears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Condition_Suffix {
            get {
                return ResourceManager.GetString("Condition_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Condition_UpdateAt {
            get {
                return ResourceManager.GetString("Condition_UpdateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Condition_UpdateBy {
            get {
                return ResourceManager.GetString("Condition_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConditionLang_ConditionID {
            get {
                return ResourceManager.GetString("ConditionLang_ConditionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConditionLang_CreateAt {
            get {
                return ResourceManager.GetString("ConditionLang_CreateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConditionLang_CreateBy {
            get {
                return ResourceManager.GetString("ConditionLang_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConditionLang_LangID {
            get {
                return ResourceManager.GetString("ConditionLang_LangID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConditionLang_Name {
            get {
                return ResourceManager.GetString("ConditionLang_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConditionLang_UpdateAt {
            get {
                return ResourceManager.GetString("ConditionLang_UpdateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string ConditionLang_UpdateBy {
            get {
                return ResourceManager.GetString("ConditionLang_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string KitSku_CreateAt {
            get {
                return ResourceManager.GetString("KitSku_CreateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string KitSku_CreateBy {
            get {
                return ResourceManager.GetString("KitSku_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string KitSku_ParentKit {
            get {
                return ResourceManager.GetString("KitSku_ParentKit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string KitSku_Qty {
            get {
                return ResourceManager.GetString("KitSku_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string KitSku_Sku {
            get {
                return ResourceManager.GetString("KitSku_Sku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string KitSku_UpdateAt {
            get {
                return ResourceManager.GetString("KitSku_UpdateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string KitSku_UpdateBy {
            get {
                return ResourceManager.GetString("KitSku_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Language 的當地語系化字串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Login 的當地語系化字串。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Login System 的當地語系化字串。
        /// </summary>
        public static string LoginHeader {
            get {
                return ResourceManager.GetString("LoginHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter no more than {1} characters 的當地語系化字串。
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Menu_Action {
            get {
                return ResourceManager.GetString("Menu_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Menu_Auth {
            get {
                return ResourceManager.GetString("Menu_Auth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Menu_Controller {
            get {
                return ResourceManager.GetString("Menu_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Menu_IsEnable {
            get {
                return ResourceManager.GetString("Menu_IsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Menu_MenuID {
            get {
                return ResourceManager.GetString("Menu_MenuID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Menu_Name {
            get {
                return ResourceManager.GetString("Menu_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Menu_Order {
            get {
                return ResourceManager.GetString("Menu_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Menu_PrevID {
            get {
                return ResourceManager.GetString("Menu_PrevID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string MenuLang_CreateAt {
            get {
                return ResourceManager.GetString("MenuLang_CreateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string MenuLang_CreateBy {
            get {
                return ResourceManager.GetString("MenuLang_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string MenuLang_LangID {
            get {
                return ResourceManager.GetString("MenuLang_LangID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string MenuLang_MenuID {
            get {
                return ResourceManager.GetString("MenuLang_MenuID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string MenuLang_Name {
            get {
                return ResourceManager.GetString("MenuLang_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string MenuLang_UpdateAt {
            get {
                return ResourceManager.GetString("MenuLang_UpdateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string MenuLang_UpdateBy {
            get {
                return ResourceManager.GetString("MenuLang_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter at least {1} characters 的當地語系化字串。
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Password 的當地語系化字串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please Enter  {0} 的當地語系化字串。
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Sku_Attribute_AttrID {
            get {
                return ResourceManager.GetString("Sku_Attribute_AttrID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Sku_Attribute_CreateAt {
            get {
                return ResourceManager.GetString("Sku_Attribute_CreateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Sku_Attribute_CreateBy {
            get {
                return ResourceManager.GetString("Sku_Attribute_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Sku_Attribute_eBay {
            get {
                return ResourceManager.GetString("Sku_Attribute_eBay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Sku_Attribute_Html {
            get {
                return ResourceManager.GetString("Sku_Attribute_Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Sku_Attribute_LangID {
            get {
                return ResourceManager.GetString("Sku_Attribute_LangID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Sku_Attribute_Sku {
            get {
                return ResourceManager.GetString("Sku_Attribute_Sku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Sku_Attribute_UpdateAt {
            get {
                return ResourceManager.GetString("Sku_Attribute_UpdateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Sku_Attribute_UpdateBy {
            get {
                return ResourceManager.GetString("Sku_Attribute_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Sku_Attribute_Value {
            get {
                return ResourceManager.GetString("Sku_Attribute_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Sku_Brand {
            get {
                return ResourceManager.GetString("Sku_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Sku_Category {
            get {
                return ResourceManager.GetString("Sku_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Sku_Condition {
            get {
                return ResourceManager.GetString("Sku_Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Sku_CreateAt {
            get {
                return ResourceManager.GetString("Sku_CreateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Sku_CreateBy {
            get {
                return ResourceManager.GetString("Sku_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Sku_EAN {
            get {
                return ResourceManager.GetString("Sku_EAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Sku_ID {
            get {
                return ResourceManager.GetString("Sku_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Sku_IsEnable {
            get {
                return ResourceManager.GetString("Sku_IsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Sku_ParentSku {
            get {
                return ResourceManager.GetString("Sku_ParentSku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Sku_Replenishable {
            get {
                return ResourceManager.GetString("Sku_Replenishable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Sku_Status {
            get {
                return ResourceManager.GetString("Sku_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Sku_Type {
            get {
                return ResourceManager.GetString("Sku_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Sku_UPC {
            get {
                return ResourceManager.GetString("Sku_UPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Sku_UpdateAt {
            get {
                return ResourceManager.GetString("Sku_UpdateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string Sku_UpdateBy {
            get {
                return ResourceManager.GetString("Sku_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuAttribute_CreateAt {
            get {
                return ResourceManager.GetString("SkuAttribute_CreateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuAttribute_CreateBy {
            get {
                return ResourceManager.GetString("SkuAttribute_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuAttribute_ID {
            get {
                return ResourceManager.GetString("SkuAttribute_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuAttribute_IsEnable {
            get {
                return ResourceManager.GetString("SkuAttribute_IsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuAttribute_Property {
            get {
                return ResourceManager.GetString("SkuAttribute_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuAttribute_Type {
            get {
                return ResourceManager.GetString("SkuAttribute_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuAttribute_UpdateAt {
            get {
                return ResourceManager.GetString("SkuAttribute_UpdateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuAttribute_UpdateBy {
            get {
                return ResourceManager.GetString("SkuAttribute_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuAttributeLang_AttrID {
            get {
                return ResourceManager.GetString("SkuAttributeLang_AttrID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuAttributeLang_CreateAt {
            get {
                return ResourceManager.GetString("SkuAttributeLang_CreateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuAttributeLang_CreateBy {
            get {
                return ResourceManager.GetString("SkuAttributeLang_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuAttributeLang_LangID {
            get {
                return ResourceManager.GetString("SkuAttributeLang_LangID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuAttributeLang_Name {
            get {
                return ResourceManager.GetString("SkuAttributeLang_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuAttributeLang_UpdateAt {
            get {
                return ResourceManager.GetString("SkuAttributeLang_UpdateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuAttributeLang_UpdateBy {
            get {
                return ResourceManager.GetString("SkuAttributeLang_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuAttributeType_CreateAt {
            get {
                return ResourceManager.GetString("SkuAttributeType_CreateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuAttributeType_CreateBy {
            get {
                return ResourceManager.GetString("SkuAttributeType_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuAttributeType_ID {
            get {
                return ResourceManager.GetString("SkuAttributeType_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuAttributeType_IsEnable {
            get {
                return ResourceManager.GetString("SkuAttributeType_IsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuAttributeType_Name {
            get {
                return ResourceManager.GetString("SkuAttributeType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuAttributeType_Order {
            get {
                return ResourceManager.GetString("SkuAttributeType_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuAttributeType_UpdateAt {
            get {
                return ResourceManager.GetString("SkuAttributeType_UpdateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuAttributeType_UpdateBy {
            get {
                return ResourceManager.GetString("SkuAttributeType_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuLang_CreateAt {
            get {
                return ResourceManager.GetString("SkuLang_CreateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuLang_CreateBy {
            get {
                return ResourceManager.GetString("SkuLang_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuLang_LangID {
            get {
                return ResourceManager.GetString("SkuLang_LangID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuLang_Models {
            get {
                return ResourceManager.GetString("SkuLang_Models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuLang_Name {
            get {
                return ResourceManager.GetString("SkuLang_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuLang_Sku {
            get {
                return ResourceManager.GetString("SkuLang_Sku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuLang_UpdateAt {
            get {
                return ResourceManager.GetString("SkuLang_UpdateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuLang_UpdateBy {
            get {
                return ResourceManager.GetString("SkuLang_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuPicture_CreateAt {
            get {
                return ResourceManager.GetString("SkuPicture_CreateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuPicture_CreateBy {
            get {
                return ResourceManager.GetString("SkuPicture_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuPicture_FileName {
            get {
                return ResourceManager.GetString("SkuPicture_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuPicture_FileSize {
            get {
                return ResourceManager.GetString("SkuPicture_FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuPicture_ID {
            get {
                return ResourceManager.GetString("SkuPicture_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuPicture_IsMain {
            get {
                return ResourceManager.GetString("SkuPicture_IsMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuPicture_Order {
            get {
                return ResourceManager.GetString("SkuPicture_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuPicture_Sku {
            get {
                return ResourceManager.GetString("SkuPicture_Sku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuPicture_UpdateAt {
            get {
                return ResourceManager.GetString("SkuPicture_UpdateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuPicture_UpdateBy {
            get {
                return ResourceManager.GetString("SkuPicture_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuType_AttributeGroup {
            get {
                return ResourceManager.GetString("SkuType_AttributeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuType_CreateAt {
            get {
                return ResourceManager.GetString("SkuType_CreateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuType_CreateBy {
            get {
                return ResourceManager.GetString("SkuType_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuType_ID {
            get {
                return ResourceManager.GetString("SkuType_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuType_IsEnable {
            get {
                return ResourceManager.GetString("SkuType_IsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuType_NetoID {
            get {
                return ResourceManager.GetString("SkuType_NetoID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuType_UpdateAt {
            get {
                return ResourceManager.GetString("SkuType_UpdateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuType_UpdateBy {
            get {
                return ResourceManager.GetString("SkuType_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuTypeLang_CreateAt {
            get {
                return ResourceManager.GetString("SkuTypeLang_CreateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuTypeLang_CreateBy {
            get {
                return ResourceManager.GetString("SkuTypeLang_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuTypeLang_LangID {
            get {
                return ResourceManager.GetString("SkuTypeLang_LangID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuTypeLang_Name {
            get {
                return ResourceManager.GetString("SkuTypeLang_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuTypeLang_TypeID {
            get {
                return ResourceManager.GetString("SkuTypeLang_TypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuTypeLang_UpdateAt {
            get {
                return ResourceManager.GetString("SkuTypeLang_UpdateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        public static string SkuTypeLang_UpdateBy {
            get {
                return ResourceManager.GetString("SkuTypeLang_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 QD - SKU System 的當地語系化字串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 User Name 的當地語系化字串。
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
