//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrderSys.Areas.SKUSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingMethod
    {
        public bool IsEnable { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public int Carrier { get; set; }
        public int API { get; set; }
        public int DirectLine { get; set; }
        public int ServiceType { get; set; }
        public int PackageType { get; set; }
        public bool IsExport { get; set; }
        public bool IsBattery { get; set; }
        public bool IsBox { get; set; }
        public string PrinterName { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
    
        public virtual API GetAPI { get; set; }
        public virtual Carrier GetCarrier { get; set; }
        public virtual DirectLine GetDirectLine { get; set; }
    }
}
