//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrderSys.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PurchaseOrderSys.App_GlobalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Account 的當地語系化字串。
        /// </summary>
        public static string AdminUser_Account {
            get {
                return ResourceManager.GetString("AdminUser_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AllowWarehouse 的當地語系化字串。
        /// </summary>
        public static string AdminUser_AllowWarehouse {
            get {
                return ResourceManager.GetString("AdminUser_AllowWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ApiPassword 的當地語系化字串。
        /// </summary>
        public static string AdminUser_ApiPassword {
            get {
                return ResourceManager.GetString("AdminUser_ApiPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ApiUserName 的當地語系化字串。
        /// </summary>
        public static string AdminUser_ApiUserName {
            get {
                return ResourceManager.GetString("AdminUser_ApiUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Auth 的當地語系化字串。
        /// </summary>
        public static string AdminUser_Auth {
            get {
                return ResourceManager.GetString("AdminUser_Auth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CreateAt 的當地語系化字串。
        /// </summary>
        public static string AdminUser_CreateAt {
            get {
                return ResourceManager.GetString("AdminUser_CreateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CreateBy 的當地語系化字串。
        /// </summary>
        public static string AdminUser_CreateBy {
            get {
                return ResourceManager.GetString("AdminUser_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Group 的當地語系化字串。
        /// </summary>
        public static string AdminUser_Group {
            get {
                return ResourceManager.GetString("AdminUser_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ID 的當地語系化字串。
        /// </summary>
        public static string AdminUser_ID {
            get {
                return ResourceManager.GetString("AdminUser_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 IsEnable 的當地語系化字串。
        /// </summary>
        public static string AdminUser_IsEnable {
            get {
                return ResourceManager.GetString("AdminUser_IsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Name 的當地語系化字串。
        /// </summary>
        public static string AdminUser_Name {
            get {
                return ResourceManager.GetString("AdminUser_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Password 的當地語系化字串。
        /// </summary>
        public static string AdminUser_Password {
            get {
                return ResourceManager.GetString("AdminUser_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 TimeZone 的當地語系化字串。
        /// </summary>
        public static string AdminUser_TimeZone {
            get {
                return ResourceManager.GetString("AdminUser_TimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 UpdateAt 的當地語系化字串。
        /// </summary>
        public static string AdminUser_UpdateAt {
            get {
                return ResourceManager.GetString("AdminUser_UpdateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 UpdateBy 的當地語系化字串。
        /// </summary>
        public static string AdminUser_UpdateBy {
            get {
                return ResourceManager.GetString("AdminUser_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Balance 的當地語系化字串。
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Carrier 的當地語系化字串。
        /// </summary>
        public static string CMCreditNote_Carrier {
            get {
                return ResourceManager.GetString("CMCreditNote_Carrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CM Date 的當地語系化字串。
        /// </summary>
        public static string CMCreditNote_CMDate {
            get {
                return ResourceManager.GetString("CMCreditNote_CMDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CM Status 的當地語系化字串。
        /// </summary>
        public static string CMCreditNote_CMStatus {
            get {
                return ResourceManager.GetString("CMCreditNote_CMStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CM Type 的當地語系化字串。
        /// </summary>
        public static string CMCreditNote_CMType {
            get {
                return ResourceManager.GetString("CMCreditNote_CMType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Company ID 的當地語系化字串。
        /// </summary>
        public static string CMCreditNote_CompanyID {
            get {
                return ResourceManager.GetString("CMCreditNote_CompanyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Create At 的當地語系化字串。
        /// </summary>
        public static string CMCreditNote_CreateAt {
            get {
                return ResourceManager.GetString("CMCreditNote_CreateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Create By 的當地語系化字串。
        /// </summary>
        public static string CMCreditNote_CreateBy {
            get {
                return ResourceManager.GetString("CMCreditNote_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Credit 的當地語系化字串。
        /// </summary>
        public static string CMCreditNote_Credit {
            get {
                return ResourceManager.GetString("CMCreditNote_Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Credit Amount 的當地語系化字串。
        /// </summary>
        public static string CMCreditNote_CreditAmount {
            get {
                return ResourceManager.GetString("CMCreditNote_CreditAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Credit Date 的當地語系化字串。
        /// </summary>
        public static string CMCreditNote_CreditDate {
            get {
                return ResourceManager.GetString("CMCreditNote_CreditDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CreditQTY 的當地語系化字串。
        /// </summary>
        public static string CMCreditNote_CreditQTY {
            get {
                return ResourceManager.GetString("CMCreditNote_CreditQTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Credit Status 的當地語系化字串。
        /// </summary>
        public static string CMCreditNote_CreditStatus {
            get {
                return ResourceManager.GetString("CMCreditNote_CreditStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ID 的當地語系化字串。
        /// </summary>
        public static string CMCreditNote_ID {
            get {
                return ResourceManager.GetString("CMCreditNote_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invoice Date 的當地語系化字串。
        /// </summary>
        public static string CMCreditNote_InvoiceDate {
            get {
                return ResourceManager.GetString("CMCreditNote_InvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invoice No 的當地語系化字串。
        /// </summary>
        public static string CMCreditNote_InvoiceNo {
            get {
                return ResourceManager.GetString("CMCreditNote_InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Is Enable 的當地語系化字串。
        /// </summary>
        public static string CMCreditNote_IsEnable {
            get {
                return ResourceManager.GetString("CMCreditNote_IsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Name 的當地語系化字串。
        /// </summary>
        public static string CMCreditNote_Name {
            get {
                return ResourceManager.GetString("CMCreditNote_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PurchaseOrder ID 的當地語系化字串。
        /// </summary>
        public static string CMCreditNote_PurchaseOrderID {
            get {
                return ResourceManager.GetString("CMCreditNote_PurchaseOrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 QTYOrdered 的當地語系化字串。
        /// </summary>
        public static string CMCreditNote_QTYOrdered {
            get {
                return ResourceManager.GetString("CMCreditNote_QTYOrdered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Received At 的當地語系化字串。
        /// </summary>
        public static string CMCreditNote_ReceivedAt {
            get {
                return ResourceManager.GetString("CMCreditNote_ReceivedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Received By 的當地語系化字串。
        /// </summary>
        public static string CMCreditNote_ReceivedBy {
            get {
                return ResourceManager.GetString("CMCreditNote_ReceivedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shipped Date 的當地語系化字串。
        /// </summary>
        public static string CMCreditNote_ShippedDate {
            get {
                return ResourceManager.GetString("CMCreditNote_ShippedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shipping Status 的當地語系化字串。
        /// </summary>
        public static string CMCreditNote_ShippingStatus {
            get {
                return ResourceManager.GetString("CMCreditNote_ShippingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SkuNo 的當地語系化字串。
        /// </summary>
        public static string CMCreditNote_SkuNo {
            get {
                return ResourceManager.GetString("CMCreditNote_SkuNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Tracking 的當地語系化字串。
        /// </summary>
        public static string CMCreditNote_Tracking {
            get {
                return ResourceManager.GetString("CMCreditNote_Tracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update At 的當地語系化字串。
        /// </summary>
        public static string CMCreditNote_UpdateAt {
            get {
                return ResourceManager.GetString("CMCreditNote_UpdateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update By 的當地語系化字串。
        /// </summary>
        public static string CMCreditNote_UpdateBy {
            get {
                return ResourceManager.GetString("CMCreditNote_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Vendor ID 的當地語系化字串。
        /// </summary>
        public static string CMCreditNote_VendorID {
            get {
                return ResourceManager.GetString("CMCreditNote_VendorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 VendorSKU 的當地語系化字串。
        /// </summary>
        public static string CMCreditNote_VendorSKU {
            get {
                return ResourceManager.GetString("CMCreditNote_VendorSKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Carrier 的當地語系化字串。
        /// </summary>
        public static string CMReplacement_Carrier {
            get {
                return ResourceManager.GetString("CMReplacement_Carrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CM Date 的當地語系化字串。
        /// </summary>
        public static string CMReplacement_CMDate {
            get {
                return ResourceManager.GetString("CMReplacement_CMDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CM Status 的當地語系化字串。
        /// </summary>
        public static string CMReplacement_CMStatus {
            get {
                return ResourceManager.GetString("CMReplacement_CMStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CM Type 的當地語系化字串。
        /// </summary>
        public static string CMReplacement_CMType {
            get {
                return ResourceManager.GetString("CMReplacement_CMType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Company ID 的當地語系化字串。
        /// </summary>
        public static string CMReplacement_CompanyID {
            get {
                return ResourceManager.GetString("CMReplacement_CompanyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Create At 的當地語系化字串。
        /// </summary>
        public static string CMReplacement_CreateAt {
            get {
                return ResourceManager.GetString("CMReplacement_CreateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Create By 的當地語系化字串。
        /// </summary>
        public static string CMReplacement_CreateBy {
            get {
                return ResourceManager.GetString("CMReplacement_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Credit Amount 的當地語系化字串。
        /// </summary>
        public static string CMReplacement_CreditAmount {
            get {
                return ResourceManager.GetString("CMReplacement_CreditAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Credit Date 的當地語系化字串。
        /// </summary>
        public static string CMReplacement_CreditDate {
            get {
                return ResourceManager.GetString("CMReplacement_CreditDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Credit Status 的當地語系化字串。
        /// </summary>
        public static string CMReplacement_CreditStatus {
            get {
                return ResourceManager.GetString("CMReplacement_CreditStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ID 的當地語系化字串。
        /// </summary>
        public static string CMReplacement_ID {
            get {
                return ResourceManager.GetString("CMReplacement_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invoice Date 的當地語系化字串。
        /// </summary>
        public static string CMReplacement_InvoiceDate {
            get {
                return ResourceManager.GetString("CMReplacement_InvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invoice No 的當地語系化字串。
        /// </summary>
        public static string CMReplacement_InvoiceNo {
            get {
                return ResourceManager.GetString("CMReplacement_InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Is Enable 的當地語系化字串。
        /// </summary>
        public static string CMReplacement_IsEnable {
            get {
                return ResourceManager.GetString("CMReplacement_IsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Name 的當地語系化字串。
        /// </summary>
        public static string CMReplacement_Name {
            get {
                return ResourceManager.GetString("CMReplacement_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PurchaseOrder D 的當地語系化字串。
        /// </summary>
        public static string CMReplacement_PurchaseOrderID {
            get {
                return ResourceManager.GetString("CMReplacement_PurchaseOrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 QTY Ordered 的當地語系化字串。
        /// </summary>
        public static string CMReplacement_QTYOrdered {
            get {
                return ResourceManager.GetString("CMReplacement_QTYOrdered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 QTY Returned 的當地語系化字串。
        /// </summary>
        public static string CMReplacement_QTYReturned {
            get {
                return ResourceManager.GetString("CMReplacement_QTYReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Received At 的當地語系化字串。
        /// </summary>
        public static string CMReplacement_ReceivedAt {
            get {
                return ResourceManager.GetString("CMReplacement_ReceivedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Received By 的當地語系化字串。
        /// </summary>
        public static string CMReplacement_ReceivedBy {
            get {
                return ResourceManager.GetString("CMReplacement_ReceivedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Replacement PO 的當地語系化字串。
        /// </summary>
        public static string CMReplacement_ReplacementPO {
            get {
                return ResourceManager.GetString("CMReplacement_ReplacementPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Serial 的當地語系化字串。
        /// </summary>
        public static string CMReplacement_Serial {
            get {
                return ResourceManager.GetString("CMReplacement_Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Serial QTY 的當地語系化字串。
        /// </summary>
        public static string CMReplacement_SerialQTY {
            get {
                return ResourceManager.GetString("CMReplacement_SerialQTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shipped Date 的當地語系化字串。
        /// </summary>
        public static string CMReplacement_ShippedDate {
            get {
                return ResourceManager.GetString("CMReplacement_ShippedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shipping Status 的當地語系化字串。
        /// </summary>
        public static string CMReplacement_ShippingStatus {
            get {
                return ResourceManager.GetString("CMReplacement_ShippingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sku No 的當地語系化字串。
        /// </summary>
        public static string CMReplacement_SkuNo {
            get {
                return ResourceManager.GetString("CMReplacement_SkuNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Tracking 的當地語系化字串。
        /// </summary>
        public static string CMReplacement_Tracking {
            get {
                return ResourceManager.GetString("CMReplacement_Tracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 UPC/EAN 的當地語系化字串。
        /// </summary>
        public static string CMReplacement_UPCEAN {
            get {
                return ResourceManager.GetString("CMReplacement_UPCEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update At 的當地語系化字串。
        /// </summary>
        public static string CMReplacement_UpdateAt {
            get {
                return ResourceManager.GetString("CMReplacement_UpdateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update By 的當地語系化字串。
        /// </summary>
        public static string CMReplacement_UpdateBy {
            get {
                return ResourceManager.GetString("CMReplacement_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Vendor ID 的當地語系化字串。
        /// </summary>
        public static string CMReplacement_VendorID {
            get {
                return ResourceManager.GetString("CMReplacement_VendorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AUD 的當地語系化字串。
        /// </summary>
        public static string CurrencyAUD {
            get {
                return ResourceManager.GetString("CurrencyAUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 TWD 的當地語系化字串。
        /// </summary>
        public static string CurrencyTWD {
            get {
                return ResourceManager.GetString("CurrencyTWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 USD 的當地語系化字串。
        /// </summary>
        public static string CurrencyUSD {
            get {
                return ResourceManager.GetString("CurrencyUSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select 的當地語系化字串。
        /// </summary>
        public static string DefaultSelect {
            get {
                return ResourceManager.GetString("DefaultSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Grand Total 的當地語系化字串。
        /// </summary>
        public static string GrandTotal {
            get {
                return ResourceManager.GetString("GrandTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Language 的當地語系化字串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Login 的當地語系化字串。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Login System 的當地語系化字串。
        /// </summary>
        public static string LoginHeader {
            get {
                return ResourceManager.GetString("LoginHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter no more than {1} characters 的當地語系化字串。
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter at least {1} characters 的當地語系化字串。
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PaidAmount 的當地語系化字串。
        /// </summary>
        public static string PaidAmount {
            get {
                return ResourceManager.GetString("PaidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Password 的當地語系化字串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Completed 的當地語系化字串。
        /// </summary>
        public static string PaymentStatusCompletedDDL {
            get {
                return ResourceManager.GetString("PaymentStatusCompletedDDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Over Paid 的當地語系化字串。
        /// </summary>
        public static string PaymentStatusOverPaidDDL {
            get {
                return ResourceManager.GetString("PaymentStatusOverPaidDDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Partially Paid 的當地語系化字串。
        /// </summary>
        public static string PaymentStatusPartiallyPaidDDL {
            get {
                return ResourceManager.GetString("PaymentStatusPartiallyPaidDDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pending 的當地語系化字串。
        /// </summary>
        public static string PaymentStatusPendingDDL {
            get {
                return ResourceManager.GetString("PaymentStatusPendingDDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Completed 的當地語系化字串。
        /// </summary>
        public static string POStatusCompletedDDL {
            get {
                return ResourceManager.GetString("POStatusCompletedDDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Opened 的當地語系化字串。
        /// </summary>
        public static string POStatusOpenedDDL {
            get {
                return ResourceManager.GetString("POStatusOpenedDDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pending 的當地語系化字串。
        /// </summary>
        public static string POStatusPendingDDL {
            get {
                return ResourceManager.GetString("POStatusPendingDDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Credit Memo 的當地語系化字串。
        /// </summary>
        public static string POTypeCreditMemoDDL {
            get {
                return ResourceManager.GetString("POTypeCreditMemoDDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Dropshp Order 的當地語系化字串。
        /// </summary>
        public static string POTypeDropshpOrderDDL {
            get {
                return ResourceManager.GetString("POTypeDropshpOrderDDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Purchase Order 的當地語系化字串。
        /// </summary>
        public static string POTypePurchaseOrderDDL {
            get {
                return ResourceManager.GetString("POTypePurchaseOrderDDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CreateAt 的當地語系化字串。
        /// </summary>
        public static string PurchaseNote_CreateAt {
            get {
                return ResourceManager.GetString("PurchaseNote_CreateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CreateBy 的當地語系化字串。
        /// </summary>
        public static string PurchaseNote_CreateBy {
            get {
                return ResourceManager.GetString("PurchaseNote_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ID 的當地語系化字串。
        /// </summary>
        public static string PurchaseNote_ID {
            get {
                return ResourceManager.GetString("PurchaseNote_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 IsEnable 的當地語系化字串。
        /// </summary>
        public static string PurchaseNote_IsEnable {
            get {
                return ResourceManager.GetString("PurchaseNote_IsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Note 的當地語系化字串。
        /// </summary>
        public static string PurchaseNote_Note {
            get {
                return ResourceManager.GetString("PurchaseNote_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PurchaseOrderID 的當地語系化字串。
        /// </summary>
        public static string PurchaseNote_PurchaseOrderID {
            get {
                return ResourceManager.GetString("PurchaseNote_PurchaseOrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 UpdateAt 的當地語系化字串。
        /// </summary>
        public static string PurchaseNote_UpdateAt {
            get {
                return ResourceManager.GetString("PurchaseNote_UpdateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 UpdateBy 的當地語系化字串。
        /// </summary>
        public static string PurchaseNote_UpdateBy {
            get {
                return ResourceManager.GetString("PurchaseNote_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Carrier 的當地語系化字串。
        /// </summary>
        public static string PurchaseOrder_Carrier {
            get {
                return ResourceManager.GetString("PurchaseOrder_Carrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Company ID 的當地語系化字串。
        /// </summary>
        public static string PurchaseOrder_CompanyID {
            get {
                return ResourceManager.GetString("PurchaseOrder_CompanyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Create At 的當地語系化字串。
        /// </summary>
        public static string PurchaseOrder_CreateAt {
            get {
                return ResourceManager.GetString("PurchaseOrder_CreateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Create By 的當地語系化字串。
        /// </summary>
        public static string PurchaseOrder_CreateBy {
            get {
                return ResourceManager.GetString("PurchaseOrder_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Currency 的當地語系化字串。
        /// </summary>
        public static string PurchaseOrder_Currency {
            get {
                return ResourceManager.GetString("PurchaseOrder_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ID 的當地語系化字串。
        /// </summary>
        public static string PurchaseOrder_ID {
            get {
                return ResourceManager.GetString("PurchaseOrder_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invoice Date 的當地語系化字串。
        /// </summary>
        public static string PurchaseOrder_InvoiceDate {
            get {
                return ResourceManager.GetString("PurchaseOrder_InvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invoice No 的當地語系化字串。
        /// </summary>
        public static string PurchaseOrder_InvoiceNo {
            get {
                return ResourceManager.GetString("PurchaseOrder_InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Is Enable 的當地語系化字串。
        /// </summary>
        public static string PurchaseOrder_IsEnable {
            get {
                return ResourceManager.GetString("PurchaseOrder_IsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Name 的當地語系化字串。
        /// </summary>
        public static string PurchaseOrder_Name {
            get {
                return ResourceManager.GetString("PurchaseOrder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Paid Amount 的當地語系化字串。
        /// </summary>
        public static string PurchaseOrder_PaidAmount {
            get {
                return ResourceManager.GetString("PurchaseOrder_PaidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Payment Date 的當地語系化字串。
        /// </summary>
        public static string PurchaseOrder_PaymentDate {
            get {
                return ResourceManager.GetString("PurchaseOrder_PaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Payment Proof 的當地語系化字串。
        /// </summary>
        public static string PurchaseOrder_PaymentProof {
            get {
                return ResourceManager.GetString("PurchaseOrder_PaymentProof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Payment Status 的當地語系化字串。
        /// </summary>
        public static string PurchaseOrder_PaymentStatus {
            get {
                return ResourceManager.GetString("PurchaseOrder_PaymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PO Date 的當地語系化字串。
        /// </summary>
        public static string PurchaseOrder_PODate {
            get {
                return ResourceManager.GetString("PurchaseOrder_PODate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PO Status 的當地語系化字串。
        /// </summary>
        public static string PurchaseOrder_POStatus {
            get {
                return ResourceManager.GetString("PurchaseOrder_POStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PO Type 的當地語系化字串。
        /// </summary>
        public static string PurchaseOrder_POType {
            get {
                return ResourceManager.GetString("PurchaseOrder_POType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Received At 的當地語系化字串。
        /// </summary>
        public static string PurchaseOrder_ReceivedAt {
            get {
                return ResourceManager.GetString("PurchaseOrder_ReceivedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Received By 的當地語系化字串。
        /// </summary>
        public static string PurchaseOrder_ReceivedBy {
            get {
                return ResourceManager.GetString("PurchaseOrder_ReceivedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Received Date 的當地語系化字串。
        /// </summary>
        public static string PurchaseOrder_ReceivedDate {
            get {
                return ResourceManager.GetString("PurchaseOrder_ReceivedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Receive Status 的當地語系化字串。
        /// </summary>
        public static string PurchaseOrder_ReceiveStatus {
            get {
                return ResourceManager.GetString("PurchaseOrder_ReceiveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shipped Date 的當地語系化字串。
        /// </summary>
        public static string PurchaseOrder_ShippedDate {
            get {
                return ResourceManager.GetString("PurchaseOrder_ShippedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Tax 的當地語系化字串。
        /// </summary>
        public static string PurchaseOrder_Tax {
            get {
                return ResourceManager.GetString("PurchaseOrder_Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Tracking 的當地語系化字串。
        /// </summary>
        public static string PurchaseOrder_Tracking {
            get {
                return ResourceManager.GetString("PurchaseOrder_Tracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update At 的當地語系化字串。
        /// </summary>
        public static string PurchaseOrder_UpdateAt {
            get {
                return ResourceManager.GetString("PurchaseOrder_UpdateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update By 的當地語系化字串。
        /// </summary>
        public static string PurchaseOrder_UpdateBy {
            get {
                return ResourceManager.GetString("PurchaseOrder_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Vendor ID 的當地語系化字串。
        /// </summary>
        public static string PurchaseOrder_VendorID {
            get {
                return ResourceManager.GetString("PurchaseOrder_VendorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Warehouse 的當地語系化字串。
        /// </summary>
        public static string PurchaseOrder_Warehouse {
            get {
                return ResourceManager.GetString("PurchaseOrder_Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Create At 的當地語系化字串。
        /// </summary>
        public static string PurchaseSKU_CreateAt {
            get {
                return ResourceManager.GetString("PurchaseSKU_CreateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Create By 的當地語系化字串。
        /// </summary>
        public static string PurchaseSKU_CreateBy {
            get {
                return ResourceManager.GetString("PurchaseSKU_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Credit 的當地語系化字串。
        /// </summary>
        public static string PurchaseSKU_Credit {
            get {
                return ResourceManager.GetString("PurchaseSKU_Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Discount 的當地語系化字串。
        /// </summary>
        public static string PurchaseSKU_Discount {
            get {
                return ResourceManager.GetString("PurchaseSKU_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Discounted Price 的當地語系化字串。
        /// </summary>
        public static string PurchaseSKU_DiscountedPrice {
            get {
                return ResourceManager.GetString("PurchaseSKU_DiscountedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ID 的當地語系化字串。
        /// </summary>
        public static string PurchaseSKU_ID {
            get {
                return ResourceManager.GetString("PurchaseSKU_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Is Enable 的當地語系化字串。
        /// </summary>
        public static string PurchaseSKU_IsEnable {
            get {
                return ResourceManager.GetString("PurchaseSKU_IsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Name 的當地語系化字串。
        /// </summary>
        public static string PurchaseSKU_Name {
            get {
                return ResourceManager.GetString("PurchaseSKU_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Other 的當地語系化字串。
        /// </summary>
        public static string PurchaseSKU_Other {
            get {
                return ResourceManager.GetString("PurchaseSKU_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Price 的當地語系化字串。
        /// </summary>
        public static string PurchaseSKU_Price {
            get {
                return ResourceManager.GetString("PurchaseSKU_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Purchase Order ID 的當地語系化字串。
        /// </summary>
        public static string PurchaseSKU_PurchaseOrderID {
            get {
                return ResourceManager.GetString("PurchaseSKU_PurchaseOrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 QTY Fulfilled 的當地語系化字串。
        /// </summary>
        public static string PurchaseSKU_QTYFulfilled {
            get {
                return ResourceManager.GetString("PurchaseSKU_QTYFulfilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 QTY Ordered 的當地語系化字串。
        /// </summary>
        public static string PurchaseSKU_QTYOrdered {
            get {
                return ResourceManager.GetString("PurchaseSKU_QTYOrdered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 QTY Received 的當地語系化字串。
        /// </summary>
        public static string PurchaseSKU_QTYReceived {
            get {
                return ResourceManager.GetString("PurchaseSKU_QTYReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Received At 的當地語系化字串。
        /// </summary>
        public static string PurchaseSKU_ReceivedAt {
            get {
                return ResourceManager.GetString("PurchaseSKU_ReceivedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Received By 的當地語系化字串。
        /// </summary>
        public static string PurchaseSKU_ReceivedBy {
            get {
                return ResourceManager.GetString("PurchaseSKU_ReceivedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shipping Cost 的當地語系化字串。
        /// </summary>
        public static string PurchaseSKU_ShippingCost {
            get {
                return ResourceManager.GetString("PurchaseSKU_ShippingCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sku No 的當地語系化字串。
        /// </summary>
        public static string PurchaseSKU_SkuNo {
            get {
                return ResourceManager.GetString("PurchaseSKU_SkuNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Total Refunded 的當地語系化字串。
        /// </summary>
        public static string PurchaseSKU_TotalRefunded {
            get {
                return ResourceManager.GetString("PurchaseSKU_TotalRefunded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update At 的當地語系化字串。
        /// </summary>
        public static string PurchaseSKU_UpdateAt {
            get {
                return ResourceManager.GetString("PurchaseSKU_UpdateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update By 的當地語系化字串。
        /// </summary>
        public static string PurchaseSKU_UpdateBy {
            get {
                return ResourceManager.GetString("PurchaseSKU_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Vendor SKU 的當地語系化字串。
        /// </summary>
        public static string PurchaseSKU_VendorSKU {
            get {
                return ResourceManager.GetString("PurchaseSKU_VendorSKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 QTY 的當地語系化字串。
        /// </summary>
        public static string QTY {
            get {
                return ResourceManager.GetString("QTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Completed 的當地語系化字串。
        /// </summary>
        public static string ReceiveStatusCompletedDDL {
            get {
                return ResourceManager.GetString("ReceiveStatusCompletedDDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Over Received 的當地語系化字串。
        /// </summary>
        public static string ReceiveStatusOverReceivedDDL {
            get {
                return ResourceManager.GetString("ReceiveStatusOverReceivedDDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Partially Received 的當地語系化字串。
        /// </summary>
        public static string ReceiveStatusPartiallyReceivedDDL {
            get {
                return ResourceManager.GetString("ReceiveStatusPartiallyReceivedDDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pending 的當地語系化字串。
        /// </summary>
        public static string ReceiveStatusPendingDDL {
            get {
                return ResourceManager.GetString("ReceiveStatusPendingDDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please Enter  {0} 的當地語系化字串。
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Create At 的當地語系化字串。
        /// </summary>
        public static string SerialsLlist_CreateAt {
            get {
                return ResourceManager.GetString("SerialsLlist_CreateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CreateBy 的當地語系化字串。
        /// </summary>
        public static string SerialsLlist_CreateBy {
            get {
                return ResourceManager.GetString("SerialsLlist_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ID 的當地語系化字串。
        /// </summary>
        public static string SerialsLlist_ID {
            get {
                return ResourceManager.GetString("SerialsLlist_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Purchase SKU ID 的當地語系化字串。
        /// </summary>
        public static string SerialsLlist_PurchaseSKUID {
            get {
                return ResourceManager.GetString("SerialsLlist_PurchaseSKUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Received At 的當地語系化字串。
        /// </summary>
        public static string SerialsLlist_ReceivedAt {
            get {
                return ResourceManager.GetString("SerialsLlist_ReceivedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Received By 的當地語系化字串。
        /// </summary>
        public static string SerialsLlist_ReceivedBy {
            get {
                return ResourceManager.GetString("SerialsLlist_ReceivedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Serials No 的當地語系化字串。
        /// </summary>
        public static string SerialsLlist_SerialsNo {
            get {
                return ResourceManager.GetString("SerialsLlist_SerialsNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Serials Type 的當地語系化字串。
        /// </summary>
        public static string SerialsLlist_SerialsType {
            get {
                return ResourceManager.GetString("SerialsLlist_SerialsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update At 的當地語系化字串。
        /// </summary>
        public static string SerialsLlist_UpdateAt {
            get {
                return ResourceManager.GetString("SerialsLlist_UpdateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update By 的當地語系化字串。
        /// </summary>
        public static string SerialsLlist_UpdateBy {
            get {
                return ResourceManager.GetString("SerialsLlist_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Status 的當地語系化字串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 QD - SKU System 的當地語系化字串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Carrier 的當地語系化字串。
        /// </summary>
        public static string Transfer_Carrier {
            get {
                return ResourceManager.GetString("Transfer_Carrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CreateAt 的當地語系化字串。
        /// </summary>
        public static string Transfer_CreateAt {
            get {
                return ResourceManager.GetString("Transfer_CreateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CreateBy 的當地語系化字串。
        /// </summary>
        public static string Transfer_CreateBy {
            get {
                return ResourceManager.GetString("Transfer_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ExternalTra 的當地語系化字串。
        /// </summary>
        public static string Transfer_ExternalTra {
            get {
                return ResourceManager.GetString("Transfer_ExternalTra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FromWID 的當地語系化字串。
        /// </summary>
        public static string Transfer_FromWID {
            get {
                return ResourceManager.GetString("Transfer_FromWID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ID 的當地語系化字串。
        /// </summary>
        public static string Transfer_ID {
            get {
                return ResourceManager.GetString("Transfer_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Interim 的當地語系化字串。
        /// </summary>
        public static string Transfer_Interim {
            get {
                return ResourceManager.GetString("Transfer_Interim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 IsEnable 的當地語系化字串。
        /// </summary>
        public static string Transfer_IsEnable {
            get {
                return ResourceManager.GetString("Transfer_IsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Status 的當地語系化字串。
        /// </summary>
        public static string Transfer_Status {
            get {
                return ResourceManager.GetString("Transfer_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Title 的當地語系化字串。
        /// </summary>
        public static string Transfer_Title {
            get {
                return ResourceManager.GetString("Transfer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 TotalQTY 的當地語系化字串。
        /// </summary>
        public static string Transfer_TotalQTY {
            get {
                return ResourceManager.GetString("Transfer_TotalQTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ToWID 的當地語系化字串。
        /// </summary>
        public static string Transfer_ToWID {
            get {
                return ResourceManager.GetString("Transfer_ToWID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Tracking 的當地語系化字串。
        /// </summary>
        public static string Transfer_Tracking {
            get {
                return ResourceManager.GetString("Transfer_Tracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 UpdateAt 的當地語系化字串。
        /// </summary>
        public static string Transfer_UpdateAt {
            get {
                return ResourceManager.GetString("Transfer_UpdateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 UpdateBy 的當地語系化字串。
        /// </summary>
        public static string Transfer_UpdateBy {
            get {
                return ResourceManager.GetString("Transfer_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 User Name 的當地語系化字串。
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Address 的當地語系化字串。
        /// </summary>
        public static string VendorLIst_Address {
            get {
                return ResourceManager.GetString("VendorLIst_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CreateAt 的當地語系化字串。
        /// </summary>
        public static string VendorLIst_CreateAt {
            get {
                return ResourceManager.GetString("VendorLIst_CreateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CreateBy 的當地語系化字串。
        /// </summary>
        public static string VendorLIst_CreateBy {
            get {
                return ResourceManager.GetString("VendorLIst_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Currency 的當地語系化字串。
        /// </summary>
        public static string VendorLIst_Currency {
            get {
                return ResourceManager.GetString("VendorLIst_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 DelAt 的當地語系化字串。
        /// </summary>
        public static string VendorLIst_DelAt {
            get {
                return ResourceManager.GetString("VendorLIst_DelAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 DelBy 的當地語系化字串。
        /// </summary>
        public static string VendorLIst_DelBy {
            get {
                return ResourceManager.GetString("VendorLIst_DelBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fax 的當地語系化字串。
        /// </summary>
        public static string VendorLIst_Fax {
            get {
                return ResourceManager.GetString("VendorLIst_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ID 的當地語系化字串。
        /// </summary>
        public static string VendorLIst_ID {
            get {
                return ResourceManager.GetString("VendorLIst_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 IsEnable 的當地語系化字串。
        /// </summary>
        public static string VendorLIst_IsEnable {
            get {
                return ResourceManager.GetString("VendorLIst_IsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Name 的當地語系化字串。
        /// </summary>
        public static string VendorLIst_Name {
            get {
                return ResourceManager.GetString("VendorLIst_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Phone 的當地語系化字串。
        /// </summary>
        public static string VendorLIst_Phone {
            get {
                return ResourceManager.GetString("VendorLIst_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Principal 的當地語系化字串。
        /// </summary>
        public static string VendorLIst_Principal {
            get {
                return ResourceManager.GetString("VendorLIst_Principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Tax 的當地語系化字串。
        /// </summary>
        public static string VendorLIst_Tax {
            get {
                return ResourceManager.GetString("VendorLIst_Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 TEL 的當地語系化字串。
        /// </summary>
        public static string VendorLIst_TEL {
            get {
                return ResourceManager.GetString("VendorLIst_TEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 UpdateAt 的當地語系化字串。
        /// </summary>
        public static string VendorLIst_UpdateAt {
            get {
                return ResourceManager.GetString("VendorLIst_UpdateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 UpdateBy 的當地語系化字串。
        /// </summary>
        public static string VendorLIst_UpdateBy {
            get {
                return ResourceManager.GetString("VendorLIst_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 VendorNo 的當地語系化字串。
        /// </summary>
        public static string VendorLIst_VendorNo {
            get {
                return ResourceManager.GetString("VendorLIst_VendorNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Company 的當地語系化字串。
        /// </summary>
        public static string Warehouse_Company {
            get {
                return ResourceManager.GetString("Warehouse_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Countries 的當地語系化字串。
        /// </summary>
        public static string Warehouse_Countries {
            get {
                return ResourceManager.GetString("Warehouse_Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CreateAt 的當地語系化字串。
        /// </summary>
        public static string Warehouse_CreateAt {
            get {
                return ResourceManager.GetString("Warehouse_CreateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CreateBy 的當地語系化字串。
        /// </summary>
        public static string Warehouse_CreateBy {
            get {
                return ResourceManager.GetString("Warehouse_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fulfillable 的當地語系化字串。
        /// </summary>
        public static string Warehouse_Fulfillable {
            get {
                return ResourceManager.GetString("Warehouse_Fulfillable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ID 的當地語系化字串。
        /// </summary>
        public static string Warehouse_ID {
            get {
                return ResourceManager.GetString("Warehouse_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 IsDefault 的當地語系化字串。
        /// </summary>
        public static string Warehouse_IsDefault {
            get {
                return ResourceManager.GetString("Warehouse_IsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 IsEnable 的當地語系化字串。
        /// </summary>
        public static string Warehouse_IsEnable {
            get {
                return ResourceManager.GetString("Warehouse_IsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 IsSellable 的當地語系化字串。
        /// </summary>
        public static string Warehouse_IsSellable {
            get {
                return ResourceManager.GetString("Warehouse_IsSellable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Location 的當地語系化字串。
        /// </summary>
        public static string Warehouse_Location {
            get {
                return ResourceManager.GetString("Warehouse_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Marketplace 的當地語系化字串。
        /// </summary>
        public static string Warehouse_Marketplace {
            get {
                return ResourceManager.GetString("Warehouse_Marketplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Name 的當地語系化字串。
        /// </summary>
        public static string Warehouse_Name {
            get {
                return ResourceManager.GetString("Warehouse_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Type 的當地語系化字串。
        /// </summary>
        public static string Warehouse_Type {
            get {
                return ResourceManager.GetString("Warehouse_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 UpdateAt 的當地語系化字串。
        /// </summary>
        public static string Warehouse_UpdateAt {
            get {
                return ResourceManager.GetString("Warehouse_UpdateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 UpdateBy 的當地語系化字串。
        /// </summary>
        public static string Warehouse_UpdateBy {
            get {
                return ResourceManager.GetString("Warehouse_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WinitWarehouse 的當地語系化字串。
        /// </summary>
        public static string Warehouse_WinitWarehouse {
            get {
                return ResourceManager.GetString("Warehouse_WinitWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AdminUserID 的當地語系化字串。
        /// </summary>
        public static string WarehouseUser_AdminUserID {
            get {
                return ResourceManager.GetString("WarehouseUser_AdminUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CreateAt 的當地語系化字串。
        /// </summary>
        public static string WarehouseUser_CreateAt {
            get {
                return ResourceManager.GetString("WarehouseUser_CreateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CreateBy 的當地語系化字串。
        /// </summary>
        public static string WarehouseUser_CreateBy {
            get {
                return ResourceManager.GetString("WarehouseUser_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ID 的當地語系化字串。
        /// </summary>
        public static string WarehouseUser_ID {
            get {
                return ResourceManager.GetString("WarehouseUser_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 IsEnable 的當地語系化字串。
        /// </summary>
        public static string WarehouseUser_IsEnable {
            get {
                return ResourceManager.GetString("WarehouseUser_IsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Purview 的當地語系化字串。
        /// </summary>
        public static string WarehouseUser_Purview {
            get {
                return ResourceManager.GetString("WarehouseUser_Purview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 UpdateAt 的當地語系化字串。
        /// </summary>
        public static string WarehouseUser_UpdateAt {
            get {
                return ResourceManager.GetString("WarehouseUser_UpdateAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 UpdateBy 的當地語系化字串。
        /// </summary>
        public static string WarehouseUser_UpdateBy {
            get {
                return ResourceManager.GetString("WarehouseUser_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WarehouseID 的當地語系化字串。
        /// </summary>
        public static string WarehouseUser_WarehouseID {
            get {
                return ResourceManager.GetString("WarehouseUser_WarehouseID", resourceCulture);
            }
        }
    }
}
