//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrderSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMCreditNote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CMCreditNote()
        {
            this.PurchaseSKU = new HashSet<PurchaseSKU>();
        }
    
        public bool IsEnable { get; set; }
        public int ID { get; set; }
        public Nullable<int> PurchaseOrderID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string InvoiceNo { get; set; }
        public string CMStatus { get; set; }
        public string CMType { get; set; }
        public Nullable<System.DateTime> CMDate { get; set; }
        public string ShippingStatus { get; set; }
        public Nullable<System.DateTime> ShippedDate { get; set; }
        public string Carrier { get; set; }
        public string Tracking { get; set; }
        public string CreditStatus { get; set; }
        public Nullable<System.DateTime> CreditDate { get; set; }
        public Nullable<decimal> CreditAmount { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string ReceivedBy { get; set; }
        public Nullable<System.DateTime> ReceivedAt { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseSKU> PurchaseSKU { get; set; }
    }
}
