//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrderSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory
    {
        public int WarehouseID { get; set; }
        public string SkuID { get; set; }
        public int Fulfillable { get; set; }
        public int Awaiting { get; set; }
        public int UnfulfillableTransit { get; set; }
        public int TotalVelocity { get; set; }
        public int Aggregate { get; set; }
        public int TransferOutQTY { get; set; }
        public int TransferInQTY { get; set; }
        public int WTransferOutQTY { get; set; }
        public int WTransferInQTY { get; set; }
    
        public virtual SKU SKU { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
