//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrderSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logistic
    {
        public string Sku { get; set; }
        public int BoxID { get; set; }
        public decimal Price { get; set; }
        public double CaseWidth { get; set; }
        public double CaseLength { get; set; }
        public double CaseHeight { get; set; }
        public int CaseWeight { get; set; }
        public double ShippingWidth { get; set; }
        public double ShippingLength { get; set; }
        public double ShippingHeight { get; set; }
        public int ShippingWeight { get; set; }
        public string OriginCountry { get; set; }
        public string ImagePath { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
    
        public virtual BoxType BoxType { get; set; }
        public virtual SKU GetSku { get; set; }
    }
}
