//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrderSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.IsEnable = true;
        }
    
        public bool IsEnable { get; set; }
        public bool IsRush { get; set; }
        public int ID { get; set; }
        public Nullable<int> OrderParent { get; set; }
        public string OrderSourceID { get; set; }
        public int SCID { get; set; }
        public int Company { get; set; }
        public byte Channel { get; set; }
        public byte OrderType { get; set; }
        public byte OrderStatus { get; set; }
        public System.DateTime OrderDate { get; set; }
        public byte PaymentStatus { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public byte FulfillmentStatus { get; set; }
        public Nullable<System.DateTime> FulfilledDate { get; set; }
        public string Update_by { get; set; }
        public Nullable<System.DateTime> Update_at { get; set; }
        public string Create_by { get; set; }
        public System.DateTime Create_at { get; set; }
    
        public virtual Company GetCompany { get; set; }
    }
}
