//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrderSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.IsEnable = true;
            this.Items = new HashSet<Items>();
            this.ActionLogs = new HashSet<OrderActionLogs>();
            this.Packages = new HashSet<Packages>();
            this.Payments = new HashSet<Payments>();
            this.Addresses = new HashSet<OrderAddresses>();
            this.Serials = new HashSet<OrderSerials>();
        }
    
        public bool IsEnable { get; set; }
        public bool IsRush { get; set; }
        public int ID { get; set; }
        public Nullable<int> OrderParent { get; set; }
        public string OrderSourceID { get; set; }
        public Nullable<int> SCID { get; set; }
        public Nullable<int> RMAID { get; set; }
        public int Company { get; set; }
        public byte Channel { get; set; }
        public string CustomerID { get; set; }
        public string CustomerEmail { get; set; }
        public byte OrderType { get; set; }
        public byte OrderStatus { get; set; }
        public System.DateTime OrderDate { get; set; }
        public byte PaymentStatus { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public byte FulfillmentStatus { get; set; }
        public Nullable<System.DateTime> FulfilledDate { get; set; }
        public int ShippingTime { get; set; }
        public string BuyerNote { get; set; }
        public string Comment { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateAt { get; set; }
    
        public virtual Company GetCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Items> Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderActionLogs> ActionLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Packages> Packages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payments> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderAddresses> Addresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderSerials> Serials { get; set; }
    }
}
