//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrderSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseNote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseNote()
        {
            this.PurchaseNoteImg = new HashSet<PurchaseNoteImg>();
        }
    
        public bool IsEnable { get; set; }
        public int ID { get; set; }
        public Nullable<int> PurchaseOrderID { get; set; }
        public string Note { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string NoteType { get; set; }
        public Nullable<int> CreditMemoID { get; set; }
        public Nullable<int> TransferID { get; set; }
        public Nullable<int> RMAID { get; set; }
        public Nullable<int> RMAOrderTrackingID { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual CreditMemo CreditMemo { get; set; }
        public virtual Transfer Transfer { get; set; }
        public virtual RMA RMA { get; set; }
        public virtual RMAOrderTracking RMAOrderTracking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseNoteImg> PurchaseNoteImg { get; set; }
    }
}
