//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrderSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMASKU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RMASKU()
        {
            this.RMASerialsLlist = new HashSet<RMASerialsLlist>();
        }
    
        public bool IsEnable { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> RMAID { get; set; }
        public string SkuNo { get; set; }
        public Nullable<int> QTYOrdered { get; set; }
        public Nullable<int> ReturnedQTY { get; set; }
        public string UPCEAN { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string ReceivedBy { get; set; }
        public Nullable<System.DateTime> ReceivedAt { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public string Reason { get; set; }
    
        public virtual RMA RMA { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual SKU SKU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RMASerialsLlist> RMASerialsLlist { get; set; }
    }
}
