//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrderSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingMethods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShippingMethods()
        {
            this.IsEnable = true;
            this.GetPackage = new HashSet<Packages>();
        }
    
        public bool IsEnable { get; set; }
        public bool IsExport { get; set; }
        public bool IsBattery { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public int CarrierID { get; set; }
        public int MethodType { get; set; }
        public int BoxType { get; set; }
        public bool InBox { get; set; }
        public string ContactName { get; set; }
        public string ConpanyName { get; set; }
        public string PhoneNumber { get; set; }
        public string CountryName { get; set; }
        public string CountryCode { get; set; }
        public string City { get; set; }
        public string StreetLine1 { get; set; }
        public string StreetLine2 { get; set; }
        public string StateName { get; set; }
        public string PostalCode { get; set; }
        public string Update_by { get; set; }
        public Nullable<System.DateTime> Update_at { get; set; }
        public string Create_by { get; set; }
        public System.DateTime Create_at { get; set; }
    
        public virtual Carriers GetCarrier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Packages> GetPackage { get; set; }
    }
}
