//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrderSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorLIst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VendorLIst()
        {
            this.PurchaseOrder = new HashSet<PurchaseOrder>();
            this.Brand = new HashSet<Brand>();
        }
    
        public bool IsEnable { get; set; }
        public int ID { get; set; }
        public string VendorNo { get; set; }
        public string Name { get; set; }
        public string Principal { get; set; }
        public string Address { get; set; }
        public string TEL { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string DelBy { get; set; }
        public Nullable<System.DateTime> DelAt { get; set; }
        public string Email { get; set; }
        public string EmailCC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrder> PurchaseOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Brand> Brand { get; set; }
    }
}
