//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此原始程式碼由 xsd 版本=4.6.1055.0 自動產生。
// 
namespace NetoDeveloper
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "NetoAPI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "NetoAPI", IsNullable = false)]
    public partial class GetAccountingSystemRelatedAccountsResponse
    {

        private GetAccountingSystemRelatedAccountsRelatedAccountsRelatedAccount[][] relatedAccountsField;

        private string currentTimeField;

        private GetAccountingSystemRelatedAccountsAck ackField;

        private GetAccountingSystemRelatedAccountsMessages messagesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("RelatedAccount", typeof(GetAccountingSystemRelatedAccountsRelatedAccountsRelatedAccount), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public GetAccountingSystemRelatedAccountsRelatedAccountsRelatedAccount[][] RelatedAccounts
        {
            get
            {
                return this.relatedAccountsField;
            }
            set
            {
                this.relatedAccountsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CurrentTime
        {
            get
            {
                return this.currentTimeField;
            }
            set
            {
                this.currentTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetAccountingSystemRelatedAccountsAck Ack
        {
            get
            {
                return this.ackField;
            }
            set
            {
                this.ackField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetAccountingSystemRelatedAccountsMessages Messages
        {
            get
            {
                return this.messagesField;
            }
            set
            {
                this.messagesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "NetoAPI")]
    public partial class GetAccountingSystemRelatedAccountsRelatedAccountsRelatedAccount
    {

        private string accsw_titleField;

        private string acc_account_idField;

        private string accapi_idField;

        private string acc_account_refField;

        private string acc_account_parent_refField;

        private string acc_account_nameField;

        private string acc_account_typeField;

        private string acc_account_classField;

        private bool is_asset_accField;

        private bool is_asset_accFieldSpecified;

        private bool is_expense_accField;

        private bool is_expense_accFieldSpecified;

        private bool is_income_accField;

        private bool is_income_accFieldSpecified;

        private bool is_costofsales_accField;

        private bool is_costofsales_accFieldSpecified;

        private bool is_bank_accField;

        private bool is_bank_accFieldSpecified;

        private string acc_account_noteField;

        private string acc_account_activeField;

        private bool acc_account_is_detailField;

        private bool acc_account_is_detailFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string accsw_title
        {
            get
            {
                return this.accsw_titleField;
            }
            set
            {
                this.accsw_titleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        public string acc_account_id
        {
            get
            {
                return this.acc_account_idField;
            }
            set
            {
                this.acc_account_idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer")]
        public string accapi_id
        {
            get
            {
                return this.accapi_idField;
            }
            set
            {
                this.accapi_idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string acc_account_ref
        {
            get
            {
                return this.acc_account_refField;
            }
            set
            {
                this.acc_account_refField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string acc_account_parent_ref
        {
            get
            {
                return this.acc_account_parent_refField;
            }
            set
            {
                this.acc_account_parent_refField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string acc_account_name
        {
            get
            {
                return this.acc_account_nameField;
            }
            set
            {
                this.acc_account_nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string acc_account_type
        {
            get
            {
                return this.acc_account_typeField;
            }
            set
            {
                this.acc_account_typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string acc_account_class
        {
            get
            {
                return this.acc_account_classField;
            }
            set
            {
                this.acc_account_classField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool is_asset_acc
        {
            get
            {
                return this.is_asset_accField;
            }
            set
            {
                this.is_asset_accField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool is_asset_accSpecified
        {
            get
            {
                return this.is_asset_accFieldSpecified;
            }
            set
            {
                this.is_asset_accFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool is_expense_acc
        {
            get
            {
                return this.is_expense_accField;
            }
            set
            {
                this.is_expense_accField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool is_expense_accSpecified
        {
            get
            {
                return this.is_expense_accFieldSpecified;
            }
            set
            {
                this.is_expense_accFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool is_income_acc
        {
            get
            {
                return this.is_income_accField;
            }
            set
            {
                this.is_income_accField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool is_income_accSpecified
        {
            get
            {
                return this.is_income_accFieldSpecified;
            }
            set
            {
                this.is_income_accFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool is_costofsales_acc
        {
            get
            {
                return this.is_costofsales_accField;
            }
            set
            {
                this.is_costofsales_accField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool is_costofsales_accSpecified
        {
            get
            {
                return this.is_costofsales_accFieldSpecified;
            }
            set
            {
                this.is_costofsales_accFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool is_bank_acc
        {
            get
            {
                return this.is_bank_accField;
            }
            set
            {
                this.is_bank_accField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool is_bank_accSpecified
        {
            get
            {
                return this.is_bank_accFieldSpecified;
            }
            set
            {
                this.is_bank_accFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string acc_account_note
        {
            get
            {
                return this.acc_account_noteField;
            }
            set
            {
                this.acc_account_noteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string acc_account_active
        {
            get
            {
                return this.acc_account_activeField;
            }
            set
            {
                this.acc_account_activeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool acc_account_is_detail
        {
            get
            {
                return this.acc_account_is_detailField;
            }
            set
            {
                this.acc_account_is_detailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool acc_account_is_detailSpecified
        {
            get
            {
                return this.acc_account_is_detailFieldSpecified;
            }
            set
            {
                this.acc_account_is_detailFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "NetoAPI")]
    public enum GetAccountingSystemRelatedAccountsAck
    {

        /// <remarks/>
        Error,

        /// <remarks/>
        Warning,

        /// <remarks/>
        Success,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "NetoAPI")]
    public partial class GetAccountingSystemRelatedAccountsMessages
    {

        private GetAccountingSystemRelatedAccountsMessagesError[] errorField;

        private GetAccountingSystemRelatedAccountsMessagesWarning[] warningField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Error", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetAccountingSystemRelatedAccountsMessagesError[] Error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Warning", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetAccountingSystemRelatedAccountsMessagesWarning[] Warning
        {
            get
            {
                return this.warningField;
            }
            set
            {
                this.warningField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "NetoAPI")]
    public partial class GetAccountingSystemRelatedAccountsMessagesError
    {

        private string messageField;

        private string severityCodeField;

        private string descriptionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SeverityCode
        {
            get
            {
                return this.severityCodeField;
            }
            set
            {
                this.severityCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "NetoAPI")]
    public partial class GetAccountingSystemRelatedAccountsMessagesWarning
    {

        private string messageField;

        private string severityCodeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SeverityCode
        {
            get
            {
                return this.severityCodeField;
            }
            set
            {
                this.severityCodeField = value;
            }
        }
    }
}
