//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此原始程式碼由 xsd 版本=4.6.1055.0 自動產生。
// 
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace NetoDeveloper
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="NetoAPI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="NetoAPI", IsNullable=false)]
    public partial class GetCustomerResponse {
        
        private GetCustomerResponseCustomer[] customerField;
        
        private string currentTimeField;
        
        private GetCustomerResponseAck ackField;
        
        private GetCustomerResponseMessages messagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Customer", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetCustomerResponseCustomer[] Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CurrentTime {
            get {
                return this.currentTimeField;
            }
            set {
                this.currentTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetCustomerResponseAck Ack {
            get {
                return this.ackField;
            }
            set {
                this.ackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetCustomerResponseMessages Messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="NetoAPI")]
    public partial class GetCustomerResponseCustomer {
        
        private string idField;
        
        private string usernameField;
        
        private string typeField;
        
        private string passwordField;
        
        private string emailAddressField;
        
        private string secondaryEmailAddressField;
        
        private bool newsletterSubscriberField;
        
        private bool newsletterSubscriberFieldSpecified;
        
        private string parentUsernameField;
        
        private string approvalUsernameField;
        
        private string referralUsernameField;
        
        private string referralCommissionField;
        
        private string genderField;
        
        private System.DateTime dateOfBirthField;
        
        private bool dateOfBirthFieldSpecified;
        
        private string identificationTypeField;
        
        private string identificationDetailsField;
        
        private string defaultDiscountsField;
        
        private string defaultDocumentTemplateField;
        
        private System.DateTime registrationDateField;
        
        private bool registrationDateFieldSpecified;
        
        private string internalNotesField;
        
        private string aBNField;
        
        private string websiteURLField;
        
        private decimal creditLimitField;
        
        private bool creditLimitFieldSpecified;
        
        private string defaultInvoiceTermsField;
        
        private string classification1Field;
        
        private string classification2Field;
        
        private string salesChannelField;
        
        private GetCustomerResponseCustomerShippingAddress shippingAddressField;
        
        private GetCustomerResponseCustomerBillingAddress billingAddressField;
        
        private bool activeField;
        
        private bool activeFieldSpecified;
        
        private bool onCreditHoldField;
        
        private bool onCreditHoldFieldSpecified;
        
        private string userGroupField;
        
        private string accountBalanceField;
        
        private string availableCreditField;
        
        private GetCustomerResponseCustomerAccountManager accountManagerField;
        
        private string defaultOrderTypeField;
        
        private string userCustom1Field;
        
        private string userCustom2Field;
        
        private string userCustom3Field;
        
        private string userCustom4Field;
        
        private string userCustom5Field;
        
        private string userCustom6Field;
        
        private string userCustom7Field;
        
        private string userCustom8Field;
        
        private string userCustom9Field;
        
        private string userCustom10Field;
        
        private string userCustom11Field;
        
        private string userCustom12Field;
        
        private string userCustom13Field;
        
        private string userCustom14Field;
        
        private string userCustom15Field;
        
        private string userCustom16Field;
        
        private string userCustom17Field;
        
        private string userCustom18Field;
        
        private string userCustom19Field;
        
        private string userCustom20Field;
        
        private string userCustom21Field;
        
        private string userCustom22Field;
        
        private string userCustom23Field;
        
        private string userCustom24Field;
        
        private string userCustom25Field;
        
        private string userCustom26Field;
        
        private string userCustom27Field;
        
        private string userCustom28Field;
        
        private string userCustom29Field;
        
        private string userCustom30Field;
        
        private string userCustom31Field;
        
        private string userCustom32Field;
        
        private string userCustom33Field;
        
        private string userCustom34Field;
        
        private string userCustom35Field;
        
        private string userCustom36Field;
        
        private string userCustom37Field;
        
        private string userCustom38Field;
        
        private string userCustom39Field;
        
        private string userCustom40Field;
        
        private string userCustom41Field;
        
        private string userCustom42Field;
        
        private string userCustom43Field;
        
        private string userCustom44Field;
        
        private string userCustom45Field;
        
        private string userCustom46Field;
        
        private string userCustom47Field;
        
        private string userCustom48Field;
        
        private string userCustom49Field;
        
        private string userCustom50Field;
        
        private System.DateTime dateAddedField;
        
        private bool dateAddedFieldSpecified;
        
        private System.DateTime dateAddedLocalField;
        
        private bool dateAddedLocalFieldSpecified;
        
        private System.DateTime dateAddedUTCField;
        
        private bool dateAddedUTCFieldSpecified;
        
        private System.DateTime dateUpdatedField;
        
        private bool dateUpdatedFieldSpecified;
        
        private System.DateTime dateUpdatedLocalField;
        
        private bool dateUpdatedLocalFieldSpecified;
        
        private System.DateTime dateUpdatedUTCField;
        
        private bool dateUpdatedUTCFieldSpecified;
        
        private GetCustomerResponseCustomerCustomerLog[] customerLogsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SecondaryEmailAddress {
            get {
                return this.secondaryEmailAddressField;
            }
            set {
                this.secondaryEmailAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool NewsletterSubscriber {
            get {
                return this.newsletterSubscriberField;
            }
            set {
                this.newsletterSubscriberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NewsletterSubscriberSpecified {
            get {
                return this.newsletterSubscriberFieldSpecified;
            }
            set {
                this.newsletterSubscriberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ParentUsername {
            get {
                return this.parentUsernameField;
            }
            set {
                this.parentUsernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ApprovalUsername {
            get {
                return this.approvalUsernameField;
            }
            set {
                this.approvalUsernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReferralUsername {
            get {
                return this.referralUsernameField;
            }
            set {
                this.referralUsernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReferralCommission {
            get {
                return this.referralCommissionField;
            }
            set {
                this.referralCommissionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateOfBirthSpecified {
            get {
                return this.dateOfBirthFieldSpecified;
            }
            set {
                this.dateOfBirthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdentificationType {
            get {
                return this.identificationTypeField;
            }
            set {
                this.identificationTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdentificationDetails {
            get {
                return this.identificationDetailsField;
            }
            set {
                this.identificationDetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DefaultDiscounts {
            get {
                return this.defaultDiscountsField;
            }
            set {
                this.defaultDiscountsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DefaultDocumentTemplate {
            get {
                return this.defaultDocumentTemplateField;
            }
            set {
                this.defaultDocumentTemplateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime RegistrationDate {
            get {
                return this.registrationDateField;
            }
            set {
                this.registrationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegistrationDateSpecified {
            get {
                return this.registrationDateFieldSpecified;
            }
            set {
                this.registrationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InternalNotes {
            get {
                return this.internalNotesField;
            }
            set {
                this.internalNotesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ABN {
            get {
                return this.aBNField;
            }
            set {
                this.aBNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WebsiteURL {
            get {
                return this.websiteURLField;
            }
            set {
                this.websiteURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal CreditLimit {
            get {
                return this.creditLimitField;
            }
            set {
                this.creditLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreditLimitSpecified {
            get {
                return this.creditLimitFieldSpecified;
            }
            set {
                this.creditLimitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DefaultInvoiceTerms {
            get {
                return this.defaultInvoiceTermsField;
            }
            set {
                this.defaultInvoiceTermsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Classification1 {
            get {
                return this.classification1Field;
            }
            set {
                this.classification1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Classification2 {
            get {
                return this.classification2Field;
            }
            set {
                this.classification2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SalesChannel {
            get {
                return this.salesChannelField;
            }
            set {
                this.salesChannelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetCustomerResponseCustomerShippingAddress ShippingAddress {
            get {
                return this.shippingAddressField;
            }
            set {
                this.shippingAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetCustomerResponseCustomerBillingAddress BillingAddress {
            get {
                return this.billingAddressField;
            }
            set {
                this.billingAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActiveSpecified {
            get {
                return this.activeFieldSpecified;
            }
            set {
                this.activeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool OnCreditHold {
            get {
                return this.onCreditHoldField;
            }
            set {
                this.onCreditHoldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OnCreditHoldSpecified {
            get {
                return this.onCreditHoldFieldSpecified;
            }
            set {
                this.onCreditHoldFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserGroup {
            get {
                return this.userGroupField;
            }
            set {
                this.userGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AccountBalance {
            get {
                return this.accountBalanceField;
            }
            set {
                this.accountBalanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AvailableCredit {
            get {
                return this.availableCreditField;
            }
            set {
                this.availableCreditField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetCustomerResponseCustomerAccountManager AccountManager {
            get {
                return this.accountManagerField;
            }
            set {
                this.accountManagerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DefaultOrderType {
            get {
                return this.defaultOrderTypeField;
            }
            set {
                this.defaultOrderTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom1 {
            get {
                return this.userCustom1Field;
            }
            set {
                this.userCustom1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom2 {
            get {
                return this.userCustom2Field;
            }
            set {
                this.userCustom2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom3 {
            get {
                return this.userCustom3Field;
            }
            set {
                this.userCustom3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom4 {
            get {
                return this.userCustom4Field;
            }
            set {
                this.userCustom4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom5 {
            get {
                return this.userCustom5Field;
            }
            set {
                this.userCustom5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom6 {
            get {
                return this.userCustom6Field;
            }
            set {
                this.userCustom6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom7 {
            get {
                return this.userCustom7Field;
            }
            set {
                this.userCustom7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom8 {
            get {
                return this.userCustom8Field;
            }
            set {
                this.userCustom8Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom9 {
            get {
                return this.userCustom9Field;
            }
            set {
                this.userCustom9Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom10 {
            get {
                return this.userCustom10Field;
            }
            set {
                this.userCustom10Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom11 {
            get {
                return this.userCustom11Field;
            }
            set {
                this.userCustom11Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom12 {
            get {
                return this.userCustom12Field;
            }
            set {
                this.userCustom12Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom13 {
            get {
                return this.userCustom13Field;
            }
            set {
                this.userCustom13Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom14 {
            get {
                return this.userCustom14Field;
            }
            set {
                this.userCustom14Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom15 {
            get {
                return this.userCustom15Field;
            }
            set {
                this.userCustom15Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom16 {
            get {
                return this.userCustom16Field;
            }
            set {
                this.userCustom16Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom17 {
            get {
                return this.userCustom17Field;
            }
            set {
                this.userCustom17Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom18 {
            get {
                return this.userCustom18Field;
            }
            set {
                this.userCustom18Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom19 {
            get {
                return this.userCustom19Field;
            }
            set {
                this.userCustom19Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom20 {
            get {
                return this.userCustom20Field;
            }
            set {
                this.userCustom20Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom21 {
            get {
                return this.userCustom21Field;
            }
            set {
                this.userCustom21Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom22 {
            get {
                return this.userCustom22Field;
            }
            set {
                this.userCustom22Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom23 {
            get {
                return this.userCustom23Field;
            }
            set {
                this.userCustom23Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom24 {
            get {
                return this.userCustom24Field;
            }
            set {
                this.userCustom24Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom25 {
            get {
                return this.userCustom25Field;
            }
            set {
                this.userCustom25Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom26 {
            get {
                return this.userCustom26Field;
            }
            set {
                this.userCustom26Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom27 {
            get {
                return this.userCustom27Field;
            }
            set {
                this.userCustom27Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom28 {
            get {
                return this.userCustom28Field;
            }
            set {
                this.userCustom28Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom29 {
            get {
                return this.userCustom29Field;
            }
            set {
                this.userCustom29Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom30 {
            get {
                return this.userCustom30Field;
            }
            set {
                this.userCustom30Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom31 {
            get {
                return this.userCustom31Field;
            }
            set {
                this.userCustom31Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom32 {
            get {
                return this.userCustom32Field;
            }
            set {
                this.userCustom32Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom33 {
            get {
                return this.userCustom33Field;
            }
            set {
                this.userCustom33Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom34 {
            get {
                return this.userCustom34Field;
            }
            set {
                this.userCustom34Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom35 {
            get {
                return this.userCustom35Field;
            }
            set {
                this.userCustom35Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom36 {
            get {
                return this.userCustom36Field;
            }
            set {
                this.userCustom36Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom37 {
            get {
                return this.userCustom37Field;
            }
            set {
                this.userCustom37Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom38 {
            get {
                return this.userCustom38Field;
            }
            set {
                this.userCustom38Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom39 {
            get {
                return this.userCustom39Field;
            }
            set {
                this.userCustom39Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom40 {
            get {
                return this.userCustom40Field;
            }
            set {
                this.userCustom40Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom41 {
            get {
                return this.userCustom41Field;
            }
            set {
                this.userCustom41Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom42 {
            get {
                return this.userCustom42Field;
            }
            set {
                this.userCustom42Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom43 {
            get {
                return this.userCustom43Field;
            }
            set {
                this.userCustom43Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom44 {
            get {
                return this.userCustom44Field;
            }
            set {
                this.userCustom44Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom45 {
            get {
                return this.userCustom45Field;
            }
            set {
                this.userCustom45Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom46 {
            get {
                return this.userCustom46Field;
            }
            set {
                this.userCustom46Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom47 {
            get {
                return this.userCustom47Field;
            }
            set {
                this.userCustom47Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom48 {
            get {
                return this.userCustom48Field;
            }
            set {
                this.userCustom48Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom49 {
            get {
                return this.userCustom49Field;
            }
            set {
                this.userCustom49Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCustom50 {
            get {
                return this.userCustom50Field;
            }
            set {
                this.userCustom50Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DateAdded {
            get {
                return this.dateAddedField;
            }
            set {
                this.dateAddedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateAddedSpecified {
            get {
                return this.dateAddedFieldSpecified;
            }
            set {
                this.dateAddedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DateAddedLocal {
            get {
                return this.dateAddedLocalField;
            }
            set {
                this.dateAddedLocalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateAddedLocalSpecified {
            get {
                return this.dateAddedLocalFieldSpecified;
            }
            set {
                this.dateAddedLocalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DateAddedUTC {
            get {
                return this.dateAddedUTCField;
            }
            set {
                this.dateAddedUTCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateAddedUTCSpecified {
            get {
                return this.dateAddedUTCFieldSpecified;
            }
            set {
                this.dateAddedUTCFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DateUpdated {
            get {
                return this.dateUpdatedField;
            }
            set {
                this.dateUpdatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateUpdatedSpecified {
            get {
                return this.dateUpdatedFieldSpecified;
            }
            set {
                this.dateUpdatedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DateUpdatedLocal {
            get {
                return this.dateUpdatedLocalField;
            }
            set {
                this.dateUpdatedLocalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateUpdatedLocalSpecified {
            get {
                return this.dateUpdatedLocalFieldSpecified;
            }
            set {
                this.dateUpdatedLocalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DateUpdatedUTC {
            get {
                return this.dateUpdatedUTCField;
            }
            set {
                this.dateUpdatedUTCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateUpdatedUTCSpecified {
            get {
                return this.dateUpdatedUTCFieldSpecified;
            }
            set {
                this.dateUpdatedUTCFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("CustomerLog", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GetCustomerResponseCustomerCustomerLog[] CustomerLogs {
            get {
                return this.customerLogsField;
            }
            set {
                this.customerLogsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="NetoAPI")]
    public partial class GetCustomerResponseCustomerShippingAddress {
        
        private string shipCompanyField;
        
        private string shipFaxField;
        
        private string shipStreetLine1Field;
        
        private string shipCityField;
        
        private string shipStateField;
        
        private string shipLastNameField;
        
        private string shipFirstNameField;
        
        private string shipCountryField;
        
        private string shipStreetLine2Field;
        
        private string shipPostCodeField;
        
        private string shipPhoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipCompany {
            get {
                return this.shipCompanyField;
            }
            set {
                this.shipCompanyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipFax {
            get {
                return this.shipFaxField;
            }
            set {
                this.shipFaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipStreetLine1 {
            get {
                return this.shipStreetLine1Field;
            }
            set {
                this.shipStreetLine1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipCity {
            get {
                return this.shipCityField;
            }
            set {
                this.shipCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipState {
            get {
                return this.shipStateField;
            }
            set {
                this.shipStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipLastName {
            get {
                return this.shipLastNameField;
            }
            set {
                this.shipLastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipFirstName {
            get {
                return this.shipFirstNameField;
            }
            set {
                this.shipFirstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipCountry {
            get {
                return this.shipCountryField;
            }
            set {
                this.shipCountryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipStreetLine2 {
            get {
                return this.shipStreetLine2Field;
            }
            set {
                this.shipStreetLine2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipPostCode {
            get {
                return this.shipPostCodeField;
            }
            set {
                this.shipPostCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipPhone {
            get {
                return this.shipPhoneField;
            }
            set {
                this.shipPhoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="NetoAPI")]
    public partial class GetCustomerResponseCustomerBillingAddress {
        
        private string billCompanyField;
        
        private string billFaxField;
        
        private string billStreetLine1Field;
        
        private string billCityField;
        
        private string billStateField;
        
        private string billLastNameField;
        
        private string billFirstNameField;
        
        private string billCountryField;
        
        private string billStreetLine2Field;
        
        private string billPostCodeField;
        
        private string billPhoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BillCompany {
            get {
                return this.billCompanyField;
            }
            set {
                this.billCompanyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BillFax {
            get {
                return this.billFaxField;
            }
            set {
                this.billFaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BillStreetLine1 {
            get {
                return this.billStreetLine1Field;
            }
            set {
                this.billStreetLine1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BillCity {
            get {
                return this.billCityField;
            }
            set {
                this.billCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BillState {
            get {
                return this.billStateField;
            }
            set {
                this.billStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BillLastName {
            get {
                return this.billLastNameField;
            }
            set {
                this.billLastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BillFirstName {
            get {
                return this.billFirstNameField;
            }
            set {
                this.billFirstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BillCountry {
            get {
                return this.billCountryField;
            }
            set {
                this.billCountryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BillStreetLine2 {
            get {
                return this.billStreetLine2Field;
            }
            set {
                this.billStreetLine2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BillPostCode {
            get {
                return this.billPostCodeField;
            }
            set {
                this.billPostCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BillPhone {
            get {
                return this.billPhoneField;
            }
            set {
                this.billPhoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="NetoAPI")]
    public partial class GetCustomerResponseCustomerAccountManager {
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string usernameField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="NetoAPI")]
    public partial class GetCustomerResponseCustomerCustomerLog {
        
        private string logIDField;
        
        private string customerField;
        
        private string allocatedToField;
        
        private string statusField;
        
        private System.DateTime dateRequiredFollowUpField;
        
        private System.DateTime lastContactedField;
        
        private System.DateTime lastContactedLocalField;
        
        private System.DateTime lastContactedUTCField;
        
        private string notesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string LogID {
            get {
                return this.logIDField;
            }
            set {
                this.logIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AllocatedTo {
            get {
                return this.allocatedToField;
            }
            set {
                this.allocatedToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DateRequiredFollowUp {
            get {
                return this.dateRequiredFollowUpField;
            }
            set {
                this.dateRequiredFollowUpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime LastContacted {
            get {
                return this.lastContactedField;
            }
            set {
                this.lastContactedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime LastContactedLocal {
            get {
                return this.lastContactedLocalField;
            }
            set {
                this.lastContactedLocalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime LastContactedUTC {
            get {
                return this.lastContactedUTCField;
            }
            set {
                this.lastContactedUTCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="NetoAPI")]
    public enum GetCustomerResponseAck {
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        Success,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="NetoAPI")]
    public partial class GetCustomerResponseMessages {
        
        private GetCustomerResponseMessagesError[] errorField;
        
        private GetCustomerResponseMessagesWarning[] warningField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Error", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetCustomerResponseMessagesError[] Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Warning", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetCustomerResponseMessagesWarning[] Warning {
            get {
                return this.warningField;
            }
            set {
                this.warningField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="NetoAPI")]
    public partial class GetCustomerResponseMessagesError {
        
        private string messageField;
        
        private string severityCodeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SeverityCode {
            get {
                return this.severityCodeField;
            }
            set {
                this.severityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="NetoAPI")]
    public partial class GetCustomerResponseMessagesWarning {
        
        private string messageField;
        
        private string severityCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SeverityCode {
            get {
                return this.severityCodeField;
            }
            set {
                this.severityCodeField = value;
            }
        }
    }
}
