//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此原始程式碼由 xsd 版本=4.6.1055.0 自動產生。
// 
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace NetoDeveloper
{   
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="NetoAPI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="NetoAPI", IsNullable=false)]
    public partial class GetCustomer {
        
        private GetCustomerFilter filterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetCustomerFilter Filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="NetoAPI")]
    public partial class GetCustomerFilter {
        
        private string[] usernameField;
        
        private GetCustomerFilterType[] typeField;
        
        private bool[] activeField;
        
        private string[] emailField;
        
        private string[] companyField;
        
        private GetCustomerFilterOnCreditHold[] onCreditHoldField;
        
        private bool[] newsletterSubscriberField;
        
        private string[] userGroupField;
        
        private string[] billStateField;
        
        private System.DateTime dateAddedFromField;
        
        private System.DateTime dateAddedToField;
        
        private System.DateTime dateUpdatedFromField;
        
        private System.DateTime dateUpdatedToField;
        
        private string pageField;
        
        private string limitField;
        
        private GetCustomerFilterOutputSelector[] outputSelectorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Username", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetCustomerFilterType[] Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Active", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool[] Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Email", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Company", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OnCreditHold", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetCustomerFilterOnCreditHold[] OnCreditHold {
            get {
                return this.onCreditHoldField;
            }
            set {
                this.onCreditHoldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NewsletterSubscriber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool[] NewsletterSubscriber {
            get {
                return this.newsletterSubscriberField;
            }
            set {
                this.newsletterSubscriberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UserGroup", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] UserGroup {
            get {
                return this.userGroupField;
            }
            set {
                this.userGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BillState", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] BillState {
            get {
                return this.billStateField;
            }
            set {
                this.billStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DateAddedFrom {
            get {
                return this.dateAddedFromField;
            }
            set {
                this.dateAddedFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DateAddedTo {
            get {
                return this.dateAddedToField;
            }
            set {
                this.dateAddedToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DateUpdatedFrom {
            get {
                return this.dateUpdatedFromField;
            }
            set {
                this.dateUpdatedFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DateUpdatedTo {
            get {
                return this.dateUpdatedToField;
            }
            set {
                this.dateUpdatedToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string Page {
            get {
                return this.pageField;
            }
            set {
                this.pageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string Limit {
            get {
                return this.limitField;
            }
            set {
                this.limitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OutputSelector", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetCustomerFilterOutputSelector[] OutputSelector {
            get {
                return this.outputSelectorField;
            }
            set {
                this.outputSelectorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="NetoAPI")]
    public enum GetCustomerFilterType {
        
        /// <remarks/>
        Prospect,
        
        /// <remarks/>
        Customer,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="NetoAPI")]
    public enum GetCustomerFilterOnCreditHold {
        
        /// <remarks/>
        True,
        
        /// <remarks/>
        False,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="NetoAPI")]
    public enum GetCustomerFilterOutputSelector {
        
        /// <remarks/>
        Username,
        
        /// <remarks/>
        ID,
        
        /// <remarks/>
        Type,
        
        /// <remarks/>
        Password,
        
        /// <remarks/>
        EmailAddress,
        
        /// <remarks/>
        SecondaryEmailAddress,
        
        /// <remarks/>
        NewsletterSubscriber,
        
        /// <remarks/>
        BillingAddress,
        
        /// <remarks/>
        ShippingAddress,
        
        /// <remarks/>
        ParentUsername,
        
        /// <remarks/>
        ApprovalUsername,
        
        /// <remarks/>
        ReferralUsername,
        
        /// <remarks/>
        ReferralCommission,
        
        /// <remarks/>
        Gender,
        
        /// <remarks/>
        DateOfBirth,
        
        /// <remarks/>
        IdentificationType,
        
        /// <remarks/>
        IdentificationDetails,
        
        /// <remarks/>
        DefaultDiscounts,
        
        /// <remarks/>
        DefaultDocumentTemplate,
        
        /// <remarks/>
        RegistrationDate,
        
        /// <remarks/>
        InternalNotes,
        
        /// <remarks/>
        ABN,
        
        /// <remarks/>
        WebsiteURL,
        
        /// <remarks/>
        CreditLimit,
        
        /// <remarks/>
        DefaultInvoiceTerms,
        
        /// <remarks/>
        Classification1,
        
        /// <remarks/>
        Classification2,
        
        /// <remarks/>
        SalesChannel,
        
        /// <remarks/>
        DefaultShippingAddress,
        
        /// <remarks/>
        Active,
        
        /// <remarks/>
        OnCreditHold,
        
        /// <remarks/>
        UserGroup,
        
        /// <remarks/>
        AccountBalance,
        
        /// <remarks/>
        AvailableCredit,
        
        /// <remarks/>
        AccountManager,
        
        /// <remarks/>
        DefaultOrderType,
        
        /// <remarks/>
        UserCustom1,
        
        /// <remarks/>
        UserCustom2,
        
        /// <remarks/>
        UserCustom3,
        
        /// <remarks/>
        UserCustom4,
        
        /// <remarks/>
        UserCustom5,
        
        /// <remarks/>
        UserCustom6,
        
        /// <remarks/>
        UserCustom7,
        
        /// <remarks/>
        UserCustom8,
        
        /// <remarks/>
        UserCustom9,
        
        /// <remarks/>
        UserCustom10,
        
        /// <remarks/>
        UserCustom11,
        
        /// <remarks/>
        UserCustom12,
        
        /// <remarks/>
        UserCustom13,
        
        /// <remarks/>
        UserCustom14,
        
        /// <remarks/>
        UserCustom15,
        
        /// <remarks/>
        UserCustom16,
        
        /// <remarks/>
        UserCustom17,
        
        /// <remarks/>
        UserCustom18,
        
        /// <remarks/>
        UserCustom19,
        
        /// <remarks/>
        UserCustom20,
        
        /// <remarks/>
        UserCustom21,
        
        /// <remarks/>
        UserCustom22,
        
        /// <remarks/>
        UserCustom23,
        
        /// <remarks/>
        UserCustom24,
        
        /// <remarks/>
        UserCustom25,
        
        /// <remarks/>
        UserCustom26,
        
        /// <remarks/>
        UserCustom27,
        
        /// <remarks/>
        UserCustom28,
        
        /// <remarks/>
        UserCustom29,
        
        /// <remarks/>
        UserCustom30,
        
        /// <remarks/>
        UserCustom31,
        
        /// <remarks/>
        UserCustom32,
        
        /// <remarks/>
        UserCustom33,
        
        /// <remarks/>
        UserCustom34,
        
        /// <remarks/>
        UserCustom35,
        
        /// <remarks/>
        UserCustom36,
        
        /// <remarks/>
        UserCustom37,
        
        /// <remarks/>
        UserCustom38,
        
        /// <remarks/>
        UserCustom39,
        
        /// <remarks/>
        UserCustom40,
        
        /// <remarks/>
        UserCustom41,
        
        /// <remarks/>
        UserCustom42,
        
        /// <remarks/>
        UserCustom43,
        
        /// <remarks/>
        UserCustom44,
        
        /// <remarks/>
        UserCustom45,
        
        /// <remarks/>
        UserCustom46,
        
        /// <remarks/>
        UserCustom47,
        
        /// <remarks/>
        UserCustom48,
        
        /// <remarks/>
        UserCustom49,
        
        /// <remarks/>
        UserCustom50,
        
        /// <remarks/>
        DateAdded,
        
        /// <remarks/>
        DateAddedLocal,
        
        /// <remarks/>
        DateAddedUTC,
        
        /// <remarks/>
        DateUpdated,
        
        /// <remarks/>
        DateUpdatedLocal,
        
        /// <remarks/>
        DateUpdatedUTC,
        
        /// <remarks/>
        CustomerLog,
    }
}
