//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此原始程式碼由 xsd 版本=4.6.1055.0 自動產生。
// 
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace NetoDeveloper
{
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="NetoAPI")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="NetoAPI", IsNullable=false)]
    public partial class GetCategory {
        
        private GetCategoryFilter filterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetCategoryFilter Filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="NetoAPI")]
    public partial class GetCategoryFilter {
        
        private string[] categoryIDField;
        
        private string[] parentCategoryIDField;
        
        private string[] categoryNameField;
        
        private YesNo activeField;
        
        private bool activeFieldSpecified;
        
        private YesNo onSiteMapField;
        
        private bool onSiteMapFieldSpecified;
        
        private YesNo onMenuField;
        
        private bool onMenuFieldSpecified;
        
        private YesNo allowReviewsField;
        
        private bool allowReviewsFieldSpecified;
        
        private YesNo requireLoginField;
        
        private bool requireLoginFieldSpecified;
        
        private System.DateTime datePostedFromField;
        
        private bool datePostedFromFieldSpecified;
        
        private System.DateTime datePostedToField;
        
        private bool datePostedToFieldSpecified;
        
        private System.DateTime dateUpdatedFromField;
        
        private bool dateUpdatedFromFieldSpecified;
        
        private System.DateTime dateUpdatedToField;
        
        private bool dateUpdatedToFieldSpecified;
        
        private string pageField;
        
        private string limitField;
        
        private GetCategoryFilterOutputSelector[] outputSelectorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CategoryID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string[] CategoryID {
            get {
                return this.categoryIDField;
            }
            set {
                this.categoryIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ParentCategoryID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string[] ParentCategoryID {
            get {
                return this.parentCategoryIDField;
            }
            set {
                this.parentCategoryIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CategoryName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] CategoryName {
            get {
                return this.categoryNameField;
            }
            set {
                this.categoryNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public YesNo Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActiveSpecified {
            get {
                return this.activeFieldSpecified;
            }
            set {
                this.activeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public YesNo OnSiteMap {
            get {
                return this.onSiteMapField;
            }
            set {
                this.onSiteMapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OnSiteMapSpecified {
            get {
                return this.onSiteMapFieldSpecified;
            }
            set {
                this.onSiteMapFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public YesNo OnMenu {
            get {
                return this.onMenuField;
            }
            set {
                this.onMenuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OnMenuSpecified {
            get {
                return this.onMenuFieldSpecified;
            }
            set {
                this.onMenuFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public YesNo AllowReviews {
            get {
                return this.allowReviewsField;
            }
            set {
                this.allowReviewsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllowReviewsSpecified {
            get {
                return this.allowReviewsFieldSpecified;
            }
            set {
                this.allowReviewsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public YesNo RequireLogin {
            get {
                return this.requireLoginField;
            }
            set {
                this.requireLoginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RequireLoginSpecified {
            get {
                return this.requireLoginFieldSpecified;
            }
            set {
                this.requireLoginFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DatePostedFrom {
            get {
                return this.datePostedFromField;
            }
            set {
                this.datePostedFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DatePostedFromSpecified {
            get {
                return this.datePostedFromFieldSpecified;
            }
            set {
                this.datePostedFromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DatePostedTo {
            get {
                return this.datePostedToField;
            }
            set {
                this.datePostedToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DatePostedToSpecified {
            get {
                return this.datePostedToFieldSpecified;
            }
            set {
                this.datePostedToFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DateUpdatedFrom {
            get {
                return this.dateUpdatedFromField;
            }
            set {
                this.dateUpdatedFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateUpdatedFromSpecified {
            get {
                return this.dateUpdatedFromFieldSpecified;
            }
            set {
                this.dateUpdatedFromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime DateUpdatedTo {
            get {
                return this.dateUpdatedToField;
            }
            set {
                this.dateUpdatedToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateUpdatedToSpecified {
            get {
                return this.dateUpdatedToFieldSpecified;
            }
            set {
                this.dateUpdatedToFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string Page {
            get {
                return this.pageField;
            }
            set {
                this.pageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string Limit {
            get {
                return this.limitField;
            }
            set {
                this.limitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OutputSelector", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetCategoryFilterOutputSelector[] OutputSelector {
            get {
                return this.outputSelectorField;
            }
            set {
                this.outputSelectorField = value;
            }
        }
    }
                
    /// <remarks/>
    [JsonConverter(typeof(StringEnumConverter))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="NetoAPI")]
    public enum GetCategoryFilterOutputSelector {
        
        /// <remarks/>
        CategoryID,
        
        /// <remarks/>
        ID,

        /// <remarks/>
        CategoryName,
        
        /// <remarks/>
        ParentCategoryID,
        
        /// <remarks/>
        Active,
        
        /// <remarks/>
        SortOrder,
        
        /// <remarks/>
        OnSiteMap,
        
        /// <remarks/>
        OnMenu,
        
        /// <remarks/>
        AllowReviews,
        
        /// <remarks/>
        CategoryReference,
        
        /// <remarks/>
        ShortDescription1,
        
        /// <remarks/>
        ShortDescription2,
        
        /// <remarks/>
        ShortDescription3,
        
        /// <remarks/>
        Description1,
        
        /// <remarks/>
        Description2,
        
        /// <remarks/>
        Description3,
        
        /// <remarks/>
        ExternalSource,
        
        /// <remarks/>
        ExternalReference1,
        
        /// <remarks/>
        ExternalReference2,
        
        /// <remarks/>
        ExternalReference3,
        
        /// <remarks/>
        DatePosted,
        
        /// <remarks/>
        DateUpdated,
    }
}
